### ISSUE TITLE
Gulp compilation is failing

### ISSUE THREAD

**Issue by ghost** [pocke/brainfuck-playground#14]
Any ideas?

```
[ hermanjunge: brainfuck-web ]$ gulp ts
module.js:338
    throw err;
          ^
Error: Cannot find module 'globule'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/tmp/brainfuck-web/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:16:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by pocke** [comment]
Sorry, I don't have solution for this problem.
Because this problem does not reproduce on my environment.

I think maybe the cause is version of gulp, npm, node....
Can you tell me which version?

My version

``` sh
sh-4.3$ gulp -v
[09:13:58] CLI version 3.9.0
[09:13:58] Local version 3.9.0
sh-4.3$ node -v
v0.12.7
sh-4.3$ npm -v
2.14.0
sh-4.3$ git show | head
commit 35e3e59da16ea38785e47f3cb8fa8aa874b1a691
Merge: e50ca54 7e0eff7
Author: Masataka Kuwabara <p.ck.t22@gmail.com>
Date:   Wed Aug 26 18:13:33 2015 +0900

    Merge branch 'timeout'. Closed #6
```

**Comment by pocke** [comment]
And I forgot to write one procedure.
`gulp browserify` is required after `gulp ts`.

Thanks!

**Comment by ghost** [comment]
Will arrive home and send you more information.
